-- GoodTrip [Fixed] -- hand-edited config, for players without Mod Config Menu.
--
-- Uncomment a line to pin that setting. Which value wins, strongest first:
--
--   1. this file          -- applied last on every launch, and never saved over
--   2. your saved config  -- what Mod Config Menu and in-game changes write
--   3. main.lua defaults  -- the base; editing these no longer has any effect,
--                            because your saved config is loaded on top of them
--
-- So a line here beats the menu: the menu can still change it while you play,
-- but it is not kept, and next launch this file decides again. Same for the map
-- position -- pin TopLeftX/TopLeftY and you can still drag it for the session.
--
-- Steam replaces this file when the mod updates, so keep a copy of your edits.

return {
    -- KeyboardMapEnable = true,   -- the extra minimap for keyboard and controller
    -- FastRestartEnable = true,   -- TAB + R restarts the run
    -- FollowCurseOfLost = true,   -- no teleporting under Curse of the Lost
    -- TeleportAnimation = false,  -- white flash on arrival
    -- LandAtDoor = true,          -- arrive at the door a walk would have used, familiars along
    -- QuicklyOneRoomMove = false, -- TAB + WASD steps one room
    -- AllowNeighborRoom = true,   -- trip into an uncleared room next to a cleared one
    -- AllowAnyRoom = false,       -- trip anywhere on the map, no path cleared first
    -- AllowBookmarking = true,    -- TAB + 1~9 marks and returns
    -- LastRoomShortcut = true,    -- TAB + Z returns to the last room
    -- FastTransition = false,     -- skip the room-change animation
    -- NoShootWhenClick = true,    -- clicking the map does not fire a tear
    -- FasterCursorMove = false,   -- cursor jumps a room per press instead of sliding
    -- CursorOnGameMap = false,    -- cursor rides the game's own corner map; needs REPENTOGON
    -- SnapViewOnLanding = true,   -- view follows you to the door at once; needs REPENTOGON
    -- DangerCautionCompat = true, -- colour dangerous rooms with Dangerous room! Caution
    -- FairTripTime = false,       -- charge game time for the distance travelled
    -- FairTripPath = true,        -- only trip to rooms reachable through cleared rooms
    -- DimMapInCombat = true,      -- keep the map on screen, faint, while the room is uncleared
    -- DimMapAlpha = 35,           -- how faint, in percent; 5 is the lowest allowed
    -- ShowSpecialIcons = true,    -- mirror, white fire, minecart, mine button, tinted skull (visited rooms)
    -- IgnoreMovementKeys = false, -- keep aiming while you walk
    -- SwapAnalogSticks = false,   -- aim the cursor with the movement stick
    -- MinimapScale = 10,          -- 5 = 0.5x, 10 = 1.0x, up to 25 = 2.5x
    -- TopLeftX = 100,             -- where the teleport map sits on screen
    -- TopLeftY = 100,
    -- CalibMainX = 0,             -- corner-map click calibration, in pixels
    -- CalibMirrorX = 0,
    -- CalibMainY = 0,
    -- CalibMirrorY = 0,
    -- OverlayKey = nil,           -- Keyboard.KEY_* number to open the map with
    -- OverlayKeyController = nil, -- Controller button number to open the map with
    -- ControllerAlternateZ = nil, -- controller button standing in for Z
    -- ControllerAlternateR = nil, -- controller button standing in for R
}
